# Generated by Django 6.0.5 on 2026-06-03 06:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('corporate_name', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email de Contato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('contract_number', models.CharField(max_length=50, verbose_name='Número do Contrato')),
                ('description', models.TextField(verbose_name='Descrição do Contrato')),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor do Contrato')),
                ('document', models.FileField(upload_to='contracts/%Y/%m', verbose_name='Conteúdo em Mídia')),
                ('contract_status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('SUSPENDED', 'Suspenso'), ('TERMINATED', 'Encerrado')], default='ACTIVE', max_length=15, verbose_name='Status do Contrato')),
                ('start_date', models.DateTimeField(verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(verbose_name='Data de Expiração')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='management.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ('-start_date',),
            },
        ),
    ]
